In [1]:
import pandas as pd
import numpy as np

In [2]:
minwagedf = pd.read_csv('Minimum Wage Data.csv', encoding = "ISO-8859-1")
#dataset is not utf-8 encoded. 
#Dataset was pulled from Kaggle (https://www.kaggle.com/lislejoem/us-minimum-wage-by-state-from-1968-to-2017)

In [3]:
minwagedf

,Year,State,Table_Data,Footnote,High.Value,Low.Value,CPI.Average,High.2018,Low.2018
0,1968,Alabama,...,NaN,0.00000,0.00000,34.783333,0.00,0.00
1,1968,Alaska,2.10,NaN,2.10000,2.10000,34.783333,15.12,15.12
2,1968,Arizona,18.72 - 26.40/wk(b),(b),0.66000,0.46800,34.783333,4.75,3.37
3,1968,Arkansas,1.25/day(b),(b),0.15625,0.15625,34.783333,1.12,1.12
4,1968,California,1.65(b),(b),1.65000,1.65000,34.783333,11.88,11.88
5,1968,Colorado,1.00 - 1.25(b),(b),1.25000,1.00000,34.783333,9.00,7.20
6,1968,Connecticut,1.40,NaN,1.40000,1.40000,34.783333,10.08,10.08
7,1968,Delaware,1.25,NaN,1.25000,1.25000,34.783333,9.00,9.00
8,1968,District of Columbia,1.25 - 1.40,NaN,1.40000,1.25000,34.783333,10.08,9.00
9,1968,Federal (FLSA),$1.15 & $1.60,NaN,1.60000,1.15000,34.783333,11.52,8.28
10,1968,Florida,...,NaN,0.00000,0.00000,34.783333,0.00,0.00
11,1968,Georgia,...,NaN,0.00000,0.00000,34.783333,0.00,0.00
12,1968,Guam,1.25,NaN,1.25000,1.25000,34.783333,9.00,9.00
13,1968,Hawaii,1.25,NaN,1.25000,1.25000,34.783333,9.00,9.00
14,1968,Idaho,1.15,NaN,1.15000,1.15000,34.783333,8.28,8.28
15,1968,Illinois,...,NaN,0.00000,0.00000,34.783333,0.00,0.00
16,1968,Indiana,1.15,NaN,1.15000,1.15000,34.783333,8.28,8.28
17,1968,Iowa,...,NaN,0.00000,0.00000,34.783333,0.00,0.00
18,1968,Kansas,...,NaN,0.00000,0.00000,34.783333,0.00,0.00
19,1968,Kentucky,.65 - .75(b),(b),0.75000,0.65000,34.783333,5.40,4.68
20,1968,Louisiana,...,NaN,0.00000,0.00000,34.783333,0.00,0.00
21,1968,Maine,1.40,NaN,1.40000,1.40000,34.783333,10.08,10.08
22,1968,Maryland,1.00 & 1.15,NaN,1.15000,1.00000,34.783333,8.28,7.20
23,1968,Massachusetts,1.60,NaN,1.60000,1.60000,34.783333,11.52,11.52
24,1968,Michigan,1.25,NaN,1.25000,1.25000,34.783333,9.00,9.00
25,1968,Minnesota,.70 - 1.15(b),(b),1.15000,0.70000,34.783333,8.28,5.04
26,1968,Mississippi,...,NaN,0.00000,0.00000,34.783333,0.00,0.00
27,1968,Missouri,...,NaN,0.00000,0.00000,34.783333,0.00,0.00
28,1968,Montana,...,NaN,0.00000,0.00000,34.783333,0.00,0.00
29,1968,Nebraska,1.00,NaN,1.00000,1.00000,34.783333,7.20,7.20
...,...,...,...,...,...,...,...,...,...
2720,2017,Minnesota,7.75-9.50(g),(g),9.50000,7.75000,245.119583,9.70,7.92
2721,2017,Mississippi,...,NaN,0.00000,0.00000,245.119583,0.00,0.00
2722,2017,Missouri,7.70,NaN,7.70000,7.70000,245.119583,7.87,7.87
2723,2017,Montana,8.15(g),(g),8.15000,8.15000,245.119583,8.33,8.33
2724,2017,Nebraska,9.00[c],[c],9.00000,9.00000,245.119583,9.19,9.19
2725,2017,Nevada,7.25-8.25,NaN,8.25000,7.25000,245.119583,8.43,7.41
2726,2017,New Hampshire,7.25,NaN,7.25000,7.25000,245.119583,7.41,7.41
2727,2017,New Jersey,8.44,NaN,8.44000,8.44000,245.119583,8.62,8.62
2728,2017,New Mexico,7.50,NaN,7.50000,7.50000,245.119583,7.66,7.66
2729,2017,New York,9.70,NaN,9.70000,9.70000,245.119583,9.91,9.91
2730,2017,North Carolina,7.25,NaN,7.25000,7.25000,245.119583,7.41,7.41
2731,2017,North Dakota,7.25,NaN,7.25000,7.25000,245.119583,7.41,7.41
2732,2017,Ohio,8.15,NaN,8.15000,8.15000,245.119583,8.33,8.33
2733,2017,Oklahoma,2.00-7.25(g),(g),7.25000,2.00000,245.119583,7.41,2.04
2734,2017,Oregon,9.75,NaN,9.75000,9.75000,245.119583,9.96,9.96
2735,2017,Pennsylvania,7.25,NaN,7.25000,7.25000,245.119583,7.41,7.41
2736,2017,Puerto Rico,5.08-7.25(i),(i),7.25000,5.08000,245.119583,7.41,5.19
2737,2017,Rhode Island,9.60,NaN,9.60000,9.60000,245.119583,9.81,9.81
2738,2017,South Carolina,...,NaN,0.00000,0.00000,245.119583,0.00,0.00
2739,2017,South Dakota,8.65,NaN,8.65000,8.65000,245.119583,8.84,8.84
2740,2017,Tennessee,...,NaN,0.00000,0.00000,245.119583,0.00,0.00
2741,2017,Texas,7.25,NaN,7.25000,7.25000,245.119583,7.41,7.41
2742,2017,U.S. Virgin Islands,4.30-7.25(j),(j),7.25000,4.30000,245.119583,7.41,4.39
2743,2017,Utah,7.25,NaN,7.25000,7.25000,245.119583,7.41,7.41
2744,2017,Vermont,10.00(e),(e),10.00000,10.00000,245.119583,10.22,10.22
2745,2017,Virginia,7.25[c],[c],7.25000,7.25000,245.119583,7.41,7.41
2746,2017,Washington,11.00,NaN,11.00000,11.00000,245.119583,11.24,11.24
2747,2017,West Virginia,8.75,NaN,8.75000,8.75000,245.119583,8.94,8.94
2748,2017,Wisconsin,7.25,NaN,7.25000,7.25000,245.119583,7.41,7.41
2749,2017,Wyoming,5.15,NaN,5.15000,5.15000,245.119583,5.26,5.26

Notes about the data: 

1. Table_data: The scraped, unclean data from the US Department of Labor. (represents wage/hour in USD)

2. Footnote: Is there some footnote associated with the data?

3. High Value: In instances where Table_data had multiple values, this is the higher of the two values.

4. Low Value: Lower of two values described in high value.

5. CPI Average: This is the average CPI score associated with that year.

6. High 2018: This is the High Value denoted in 2018 adjusted dollars. 

7. Low 2018: This is the Low Value denoted in 2018 adjusted dollars.

Note: Every state and territory has an entry in each year of the dataset. The dataset spans from 1968 to 2017.

In [4]:
calivingwagedf2010 = pd.read_csv('caliving-wage.csv')

In [5]:
calivingwagedf2010

,ind_id,ind_definition,reportyear,race_eth_code,race_eth_name,geotype,geotypevalue,geoname,county_name,county_fips,...,families,pct_lt_lw,LL_95CI,UL_95CI,se,rse,family_type_decile,CA_RR,livingwage,version
0,770,Living wage and percent of families with incom...,2010,1.0,AIAN,CO,6001,Alameda,Alameda,6001.0,...,320.0,22.2,NaN,NaN,NaN,NaN,NaN,0.89,22.64,9/29/2013 0:00
1,770,Living wage and percent of families with incom...,2010,2.0,Asian,CO,6001,Alameda,Alameda,6001.0,...,41863.0,13.7,NaN,NaN,NaN,NaN,NaN,0.55,22.64,9/29/2013 0:00
2,770,Living wage and percent of families with incom...,2010,3.0,AfricanAm,CO,6001,Alameda,Alameda,6001.0,...,6431.0,17.9,NaN,NaN,NaN,NaN,NaN,0.72,22.64,9/29/2013 0:00
3,770,Living wage and percent of families with incom...,2010,4.0,Latino,CO,6001,Alameda,Alameda,6001.0,...,25776.0,36.0,NaN,NaN,NaN,NaN,NaN,1.44,22.64,9/29/2013 0:00
4,770,Living wage and percent of families with incom...,2010,5.0,NHOPI,CO,6001,Alameda,Alameda,6001.0,...,1046.0,11.3,NaN,NaN,NaN,NaN,NaN,0.45,22.64,9/29/2013 0:00
5,770,Living wage and percent of families with incom...,2010,6.0,White,CO,6001,Alameda,Alameda,6001.0,...,41821.0,7.2,NaN,NaN,NaN,NaN,NaN,0.29,22.64,9/29/2013 0:00
6,770,Living wage and percent of families with incom...,2010,7.0,Multiple,CO,6001,Alameda,Alameda,6001.0,...,2445.0,13.8,NaN,NaN,NaN,NaN,NaN,0.55,22.64,9/29/2013 0:00
7,770,Living wage and percent of families with incom...,2010,8.0,Other,CO,6001,Alameda,Alameda,6001.0,...,398.0,22.1,NaN,NaN,NaN,NaN,NaN,0.89,22.64,9/29/2013 0:00
8,770,Living wage and percent of families with incom...,2010,9.0,Total,CO,6001,Alameda,Alameda,6001.0,...,120100.0,16.5,NaN,NaN,NaN,NaN,NaN,0.66,22.64,9/29/2013 0:00
9,770,Living wage and percent of families with incom...,2010,NaN,NaN,CO,6001,Alameda,Alameda,6001.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,21.30,9/29/2013 0:00
10,770,Living wage and percent of families with incom...,2010,1.0,AIAN,CO,6001,Alameda,Alameda,6001.0,...,250.0,98.5,NaN,NaN,NaN,NaN,NaN,1.28,26.83,9/29/2013 0:00
11,770,Living wage and percent of families with incom...,2010,2.0,Asian,CO,6001,Alameda,Alameda,6001.0,...,4726.0,61.3,NaN,NaN,NaN,NaN,NaN,0.79,26.83,9/29/2013 0:00
12,770,Living wage and percent of families with incom...,2010,3.0,AfricanAm,CO,6001,Alameda,Alameda,6001.0,...,12304.0,87.0,NaN,NaN,NaN,NaN,NaN,1.13,26.83,9/29/2013 0:00
13,770,Living wage and percent of families with incom...,2010,4.0,Latino,CO,6001,Alameda,Alameda,6001.0,...,8743.0,80.4,NaN,NaN,NaN,NaN,NaN,1.04,26.83,9/29/2013 0:00
14,770,Living wage and percent of families with incom...,2010,5.0,NHOPI,CO,6001,Alameda,Alameda,6001.0,...,248.0,82.0,NaN,NaN,NaN,NaN,NaN,1.06,26.83,9/29/2013 0:00
15,770,Living wage and percent of families with incom...,2010,6.0,White,CO,6001,Alameda,Alameda,6001.0,...,8376.0,55.3,NaN,NaN,NaN,NaN,NaN,0.72,26.83,9/29/2013 0:00
16,770,Living wage and percent of families with incom...,2010,7.0,Multiple,CO,6001,Alameda,Alameda,6001.0,...,1116.0,66.3,NaN,NaN,NaN,NaN,NaN,0.86,26.83,9/29/2013 0:00
17,770,Living wage and percent of families with incom...,2010,8.0,Other,CO,6001,Alameda,Alameda,6001.0,...,227.0,90.7,NaN,NaN,NaN,NaN,NaN,1.18,26.83,9/29/2013 0:00
18,770,Living wage and percent of families with incom...,2010,9.0,Total,CO,6001,Alameda,Alameda,6001.0,...,35990.0,74.1,NaN,NaN,NaN,NaN,NaN,0.96,26.83,9/29/2013 0:00
19,770,Living wage and percent of families with incom...,2010,NaN,NaN,CO,6001,Alameda,Alameda,6001.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,17.38,9/29/2013 0:00
20,770,Living wage and percent of families with incom...,2010,NaN,NaN,CO,6001,Alameda,Alameda,6001.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.51,9/29/2013 0:00
21,770,Living wage and percent of families with incom...,2010,NaN,NaN,CO,6001,Alameda,Alameda,6001.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,23.22,9/29/2013 0:00
22,770,Living wage and percent of families with incom...,2010,NaN,NaN,CO,6001,Alameda,Alameda,6001.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,26.83,9/29/2013 0:00
23,770,Living wage and percent of families with incom...,2010,NaN,NaN,CO,6001,Alameda,Alameda,6001.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,33.67,9/29/2013 0:00
24,770,Living wage and percent of families with incom...,2010,NaN,NaN,CO,6001,Alameda,Alameda,6001.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22.64,9/29/2013 0:00
25,770,Living wage and percent of families with incom...,2010,NaN,NaN,CO,6001,Alameda,Alameda,6001.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,27.67,9/29/2013 0:00
26,770,Living wage and percent of families with incom...,2010,NaN,NaN,CO,6001,Alameda,Alameda,6001.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,26.83,9/29/2013 0:00
27,770,Living wage and percent of families with incom...,2010,NaN,NaN,CO,6001,Alameda,Alameda,6001.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22.64,9/29/2013 0:00
28,770,Living wage and percent of families with incom...,2010,9.0,Total,PL,562,Alameda city,Alameda,6001.0,...,5742.0,13.2,NaN,NaN,NaN,NaN,7.0,0.53,22.64,9/29/2013 0:00
29,770,Living wage and percent of families with incom...,2010,9.0,Total,PL,562,Alameda city,Alameda,6001.0,...,1997.0,70.7,NaN,NaN,NaN,NaN,7.0,0.92,26.83,9/29/2013 0:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15839,770,Living wage and percent of families with incom...,2010,7.0,Multiple,RE,13,Shasta,NaN,NaN,...,145.0,55.2,NaN,NaN,NaN,NaN,NaN,2.21,18.62,9/29/2013 0:00
15840,770,Living wage and percent of families with incom...,2010,8.0,Other,RE,13,Shasta,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9/29/2013 0:00
15841,770,Living wage and percent of families with incom...,2010,9.0,Total,RE,13,Shasta,NaN,NaN,...,12258.0,21.8,NaN,NaN,NaN,NaN,NaN,0.87,18.62,9/29/2013 0:00
15842,770,Living wage and percent of families with incom...,2010,1.0,AIAN,RE,13,Shasta,NaN,NaN,...,115.0,98.3,NaN,NaN,NaN,NaN,NaN,1.27,22.78,9/29/2013 0:00
15843,770,Living wage and percent of families with incom...,2010,2.0,Asian,RE,13,Shasta,NaN,NaN,...,204.0,89.7,NaN,NaN,NaN,NaN,NaN,1.16,22.78,9/29/2013 0:00
15844,770,Living wage and percent of families with incom...,2010,3.0,AfricanAm,RE,13,Shasta,NaN,NaN,...,92.0,76.1,NaN,NaN,NaN,NaN,NaN,0.99,22.78,9/29/2013 0:00
15845,770,Living wage and percent of families with incom...,2010,4.0,Latino,RE,13,Shasta,NaN,NaN,...,330.0,86.2,NaN,NaN,NaN,NaN,NaN,1.12,22.78,9/29/2013 0:00
15846,770,Living wage and percent of families with incom...,2010,5.0,NHOPI,RE,13,Shasta,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9/29/2013 0:00
15847,770,Living wage and percent of families with incom...,2010,6.0,White,RE,13,Shasta,NaN,NaN,...,3966.0,82.6,NaN,NaN,NaN,NaN,NaN,1.07,22.78,9/29/2013 0:00
15848,770,Living wage and percent of families with incom...,2010,7.0,Multiple,RE,13,Shasta,NaN,NaN,...,278.0,100.0,NaN,NaN,NaN,NaN,NaN,1.30,22.78,9/29/2013 0:00
15849,770,Living wage and percent of families with incom...,2010,8.0,Other,RE,13,Shasta,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9/29/2013 0:00
15850,770,Living wage and percent of families with incom...,2010,9.0,Total,RE,13,Shasta,NaN,NaN,...,4985.0,84.3,NaN,NaN,NaN,NaN,NaN,1.09,22.78,9/29/2013 0:00
15851,770,Living wage and percent of families with incom...,2010,1.0,AIAN,RE,14,Southern California,NaN,NaN,...,3001.0,22.8,NaN,NaN,NaN,NaN,NaN,0.91,21.91,9/29/2013 0:00
15852,770,Living wage and percent of families with incom...,2010,2.0,Asian,RE,14,Southern California,NaN,NaN,...,195574.0,21.8,NaN,NaN,NaN,NaN,NaN,0.87,23.02,9/29/2013 0:00
15853,770,Living wage and percent of families with incom...,2010,3.0,AfricanAm,RE,14,Southern California,NaN,NaN,...,54392.0,19.2,NaN,NaN,NaN,NaN,NaN,0.77,22.26,9/29/2013 0:00
15854,770,Living wage and percent of families with incom...,2010,4.0,Latino,RE,14,Southern California,NaN,NaN,...,675821.0,42.6,NaN,NaN,NaN,NaN,NaN,1.71,22.46,9/29/2013 0:00
15855,770,Living wage and percent of families with incom...,2010,5.0,NHOPI,RE,14,Southern California,NaN,NaN,...,3311.0,18.7,NaN,NaN,NaN,NaN,NaN,0.75,22.62,9/29/2013 0:00
15856,770,Living wage and percent of families with incom...,2010,6.0,White,RE,14,Southern California,NaN,NaN,...,486416.0,11.0,NaN,NaN,NaN,NaN,NaN,0.44,22.68,9/29/2013 0:00
15857,770,Living wage and percent of families with incom...,2010,7.0,Multiple,RE,14,Southern California,NaN,NaN,...,15509.0,14.5,NaN,NaN,NaN,NaN,NaN,0.58,22.57,9/29/2013 0:00
15858,770,Living wage and percent of families with incom...,2010,8.0,Other,RE,14,Southern California,NaN,NaN,...,3920.0,29.4,NaN,NaN,NaN,NaN,NaN,1.18,22.37,9/29/2013 0:00
15859,770,Living wage and percent of families with incom...,2010,9.0,Total,RE,14,Southern California,NaN,NaN,...,1437956.0,27.8,NaN,NaN,NaN,NaN,NaN,1.11,22.60,9/29/2013 0:00
15860,770,Living wage and percent of families with incom...,2010,1.0,AIAN,RE,14,Southern California,NaN,NaN,...,1278.0,79.9,NaN,NaN,NaN,NaN,NaN,1.04,26.21,9/29/2013 0:00
15861,770,Living wage and percent of families with incom...,2010,2.0,Asian,RE,14,Southern California,NaN,NaN,...,29790.0,67.3,NaN,NaN,NaN,NaN,NaN,0.87,27.21,9/29/2013 0:00
15862,770,Living wage and percent of families with incom...,2010,3.0,AfricanAm,RE,14,Southern California,NaN,NaN,...,67357.0,80.4,NaN,NaN,NaN,NaN,NaN,1.04,26.63,9/29/2013 0:00
15863,770,Living wage and percent of families with incom...,2010,4.0,Latino,RE,14,Southern California,NaN,NaN,...,236158.0,84.8,NaN,NaN,NaN,NaN,NaN,1.10,26.71,9/29/2013 0:00
15864,770,Living wage and percent of families with incom...,2010,5.0,NHOPI,RE,14,Southern California,NaN,NaN,...,1201.0,66.4,NaN,NaN,NaN,NaN,NaN,0.86,26.96,9/29/2013 0:00
15865,770,Living wage and percent of families with incom...,2010,6.0,White,RE,14,Southern California,NaN,NaN,...,100248.0,62.7,NaN,NaN,NaN,NaN,NaN,0.81,26.76,9/29/2013 0:00
15866,770,Living wage and percent of families with incom...,2010,7.0,Multiple,RE,14,Southern California,NaN,NaN,...,6651.0,69.1,NaN,NaN,NaN,NaN,NaN,0.90,26.67,9/29/2013 0:00
15867,770,Living wage and percent of families with incom...,2010,8.0,Other,RE,14,Southern California,NaN,NaN,...,1752.0,75.3,NaN,NaN,NaN,NaN,NaN,0.98,26.65,9/29/2013 0:00
15868,770,Living wage and percent of families with incom...,2010,9.0,Total,RE,14,Southern California,NaN,NaN,...,444443.0,77.6,NaN,NaN,NaN,NaN,NaN,1.01,26.74,9/29/2013 0:00

In [6]:
calivingwagedf2010['reportyear'].min()
#data appears to only cover the year 2010.

2010

In [7]:
calivingwagedf2010 = calivingwagedf2010.loc[calivingwagedf2010['family_type'] == 'Adult2_Child1', ['county_name', 'livingwage']]

In [8]:
calivingwagedf2010 = calivingwagedf2010.drop_duplicates(subset = 'county_name')

In [9]:
calivingwagedf2010 = calivingwagedf2010.dropna(axis = 0)

In [16]:
calivingwagedf2010

           county_name  livingwage
9              Alameda       21.30
291             Alpine       17.92
379             Amador       19.00
493              Butte       17.43
716          Calaveras       17.43
924             Colusa       17.35
1009      Contra Costa       21.30
1535         Del Norte       17.26
1611         El Dorado       18.81
1750            Fresno       17.34
2199             Glenn       16.64
2250          Humboldt       17.81
2533          Imperial       17.38
2765              Inyo       16.98
3006              Kern       17.04
3679             Kings       16.98
3821              Lake       17.68
4036            Lassen       17.54
4087       Los Angeles       21.62
5678            Madera       17.49
5820             Marin       24.13
6184          Mariposa       17.92
6302         Mendocino       18.30
6447            Merced       17.04
6661             Modoc       17.10
6758              Mono       19.73
6819          Monterey       20.01
7177              Napa       21.10
7301            Nevada       19.39
7434            Orange       22.90
7921            Placer       18.81
8132            Plumas       17.69
8703         Riverside       19.32
9406        Sacramento       18.81
9734        San Benito       20.01
9801    San Bernardino       19.32
10342        San Diego       20.91
10959    San Francisco       24.13
10986      San Joaquin       18.13
11257  San Luis Obispo       19.70
11507        San Mateo       24.13
11886    Santa Barbara       20.43
12160      Santa Clara       21.75
12476       Santa Cruz       23.36
12765           Shasta       17.25
12997           Sierra       18.85
13055         Siskiyou       16.82
13317           Solano       20.07
13459           Sonoma       20.78
13805       Stanislaus       18.01
14133           Sutter       16.78
14215           Tehama       16.89
14363          Trinity       16.92
14448           Tulare       16.11
14929         Tuolumne       18.22
15104          Ventura       22.06
15363             Yolo       18.91
15472             Yuba       16.78

In [14]:
calivingwagedf2018 = pd.read_csv('calivingwage2018.csv')

In [17]:
calivingwagedf2018 = calivingwagedf2018.dropna()

In [18]:
calivingwagedf2018
#This dataframe represents the county-level living wage in 2018 dollars for all CA counties.

    id      County Name  Wage per hour
1    1          alameda          30.56
2    2           alpine          21.83
3    3           amador          22.92
4    4            butte          22.34
5    5        calaveras          21.97
6    6           colusa          21.67
7    7     contra costa          30.56
8    8        del norte          22.12
9    9        el dorado          23.08
10  10           fresno          22.10
11  11            glenn          21.36
12  12         humboldt          23.01
13  13         imperial          21.67
14  14             inyo          22.04
15  15             kern          21.82
16  16            kings          21.55
17  17             lake          22.29
18  18           lassen          22.30
19  19      los angeles          26.43
20  20           madera          22.14
21  21            marin          36.11
22  22         mariposa          21.95
23  23        mendocino          23.05
24  24           merced          21.37
25  25            modoc          20.75
26  26             mono          24.09
27  27         monterey          25.59
28  28             napa          26.78
29  29           nevada          24.88
30  30           orange          28.19
31  31           placer          23.08
32  32           plumas          21.73
33  33        riverside          24.14
34  34       sacramento          23.08
35  35       san benito          26.07
36  36   san bernardino          24.14
37  37        san diego          27.72
38  38    san francisco          36.11
39  39      san joaquin          22.63
40  40  san luis obispo          24.88
41  41        san mateo          36.11
42  42    santa barbara          26.49
43  43      santa clara          30.86
44  44       santa cruz          28.29
45  45           shasta          22.13
46  46           sierra          23.84
47  47         siskiyou          21.62
48  48           solano          24.78
49  49           sonoma          26.60
50  50       stanislaus          22.44
51  51           sutter          22.09
52  52           tehama          21.68
53  53          trinity          21.61
54  54           tulare          22.01
55  55         tuolomne          22.64
56  56          ventura          27.85
57  57             yolo          23.99
58  58             yuba          22.09